Quirke.CRM/Controllers/MasterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Quirke.CRM.DataContext;
using Quirke.CRM.Models;
using Quirke.CRM.Services;

namespace Quirke.CRM.Controllers
{
    [Authorize]
    public class MasterController : BaseController
    {
        #region Properties
        protected readonly IMasterService _masterService;
        protected readonly ISupplierService _supplierService;
        public MasterController(UserManager<ApplicationUser> userManager, ApplicationDbContext _context, RoleManager<IdentityRole> roleManager, IMasterService masterService, ISupplierService supplierService) : base(userManager, null, _context, roleManager)
        {
            _masterService = masterService;
            _supplierService = supplierService;
        }
        #endregion

        #region Masters

        public IActionResult Index(int id)
        {
            ViewBag.MasterTypeId = id;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetMaster(int typeId)
        {
            var masters = await _masterService.GetAllByMasterTypeIdAsync(typeId);

            var data = new
            {
                data = masters
            };

            return Json(data);
        }

        [HttpGet]
        public async Task<IActionResult> ManageMaster(int typeId, int? id)
        {
            var model = new MasterModel();
            if (id == null)
            {
                model.MasterTypeId = typeId;
            }
            else
            {
                model = await _masterService.GetByIdAsync(id.Value);
            }
            return PartialView("~/Views/Master/_ManageMasterPartial.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageMaster(MasterModel model)
        {
            if (model.Id == 0)
            {
                await _masterService.CreateAsync(model);
            }
            else
            {
                await _masterService.UpdateAsync(model);
            }
            TempData["SuccessMessage"] = "Saved successfully.";
            return RedirectToAction("Index", new { id = model.MasterTypeId });
        }

        public async Task<IActionResult> DeleteMaster(int id)
        {
            var model = await _masterService.DeleteAsync(id);
            return Json(new { result = true, msg = "Deleted successfully." });
        }
        #endregion

        #region Suppliers
        public IActionResult Suppliers()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetSuppliersData()
        {
            var suppliers = await _supplierService.GetAllSuppliersAsync();
            return Json(new { data = suppliers });
        }

        public async Task<IActionResult> ManageSupplier(int? id)
        {
            SupplierModel supplier;

            if (id.HasValue && id.Value > 0)
            {
                supplier = await _supplierService.GetSupplierByIdAsync(id.Value);
                if (supplier == null)
                {
                    return NotFound();
                }
            }
            else
            {
                supplier = new SupplierModel();
            }

            return PartialView("_ManageSuppliersPartial", supplier);
        }

        [HttpPost]
        public async Task<IActionResult> ManageSupplier(SupplierModel model)
        {
            ModelState.Remove(nameof(model.Id));

            if (!ModelState.IsValid) { return Json(null); };

            string strMessage;
            if (model.Id == 0)
            {
                strMessage = "Supplier data saved successfully";
                await _supplierService.CreateSupplierAsync(model);
            }
            else
            {
                strMessage = "Supplier data updated successfully";
            }   await _supplierService.UpdateSupplierAsync(model);

            return Json(new { result = true, msg = strMessage });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSupplier(int id)
        {
            bool result = await _supplierService.DeleteSupplierAsync(id);

            if (result)
            {
                return Json(new { result = true, msg = "Supplier deleted successfully." });
            }
            else
            {
                return Json(new { result = false, msg = "Error deleting supplier." });
            }
        }

        #endregion
    }
}

Quirke.CRM/Views/Master/Index.cshtml
@{
    ViewData["Title"] = "Masters";
    int typeId = Convert.ToInt32(ViewBag.MasterTypeId);
    string type = Enum.GetName(typeof(MasterType), typeId);
}

<section class="content pt-3">
    <div class="container-fluid">
        <div class="card card-default color-palette-box">
            <div class="card-header">
                <h1 class="card-title">Master - @type</h1>
                <button class="btn btn-primary btn-sm float-right" data-toggle="modal" data-target="#commonModalCenter" onclick="funManageMaster(null)">Add @type  &nbsp; <i class="fas fa-plus"></i></button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="brandTable" class="table table-striped table-bordered" style="width:100%">
                        <thead class="thead-dark">
                            <tr>
                                <th>Sr No.</th>
                                <th>@type Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="commonModalCenter" tabindex="-1" role="dialog" aria-labelledby="commonModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commonModalCenterTitle">@type</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divCommonModel"></div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="~/quirke/js/jquery-3.6.0.min.js"></script>

<!-- Add jQuery UI JS -->

<script src="~/quirke/js/jquery-ui.min.js"></script>
<script src="~/quirke/js/bootstrap.bundle.min.js"></script>

<script>
    var myModal = new bootstrap.Modal(document.getElementById('commonModalCenter'));
    var dtTable;
    $(document).ready(function () {
        funGridMaster();
        $(window).resize(() => {
            setTimeout(function () {
                $($.fn.dataTable.tables(true)).DataTable().columns.adjust();
            }, 200);
        });
    });

    function funGridMaster() {
        if (dtTable) {
            dtTable.destroy();
        };
        dtTable = $('#brandTable').DataTable({
            "processing": true,
            "serverSide": false,
            "ajax": {
                "url": '@Url.Action("GetMaster", "Master", new { typeId = @typeId })',
                "type": "GET",
                "datatype": "json"
            },
            "columns": [
                {
                    "data": null,
                    "className": "text-center",
                    "render": function (data, type, full, meta) {
                        return meta.row + 1;
                    }
                },
                { "data": "Name" },
                {
                    "data": null,
                    "className": "",
                    "render": function (data, type, full, meta) {
                        return '<button class="btn btn-secondary btn-sm mr-2" onclick="funManageMaster(' + full.Id + ')" >Edit  &nbsp; <i class="fas fa-pen"></i></button>' +
                            '<button class="btn btn-danger btn-sm" onclick="funDeleteMaster(' + full.Id + ')" >Delete  &nbsp; <i class="fas fa-trash"></i></button>';
                    }
                }
            ],
            fixedHeader: true,
            responsive: true,
            scrollCollapse: true,
            scrollY: '50vh',
            scrollX: true,
            deferRender: true,
            scroller: true,
            autoWidth: true,
            searching: false,
            pageLength: 10,
            lengthChange: false,
            layout: {
                topStart: {
                    buttons: []
                },
                bottom: ['paging'],
                bottomStart: null,
                bottomEnd: null,
            }
        });
    }

    function funManageMaster(_id) {

        $.ajax({
            url: '@Url.Action("ManageMaster", "Master")',
            type: 'GET',
            dataType: 'html',
            data: {
                typeId: '@typeId',
                id: _id,
            },
            success: function (data) {
                $("#divCommonModel").html('');
                $("#divCommonModel").html(data);
                myModal.show();
            },
            error: function (error) {
            }
        });
    }

    function funDeleteMaster(_id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "Do you really want to delete this record? This action cannot be undone.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '@Url.Action("DeleteMaster", "Master")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        id: _id,
                    },
                    success: function (response) {
                        if (response.result) {
                            funGridMaster();
                            Swal.fire({
                                title: 'Success!',
                                text: response.msg,
                                icon: 'success',
                                confirmButtonText: 'OK'
                            });
                        }
                    },
                    error: function (response) {
                        Swal.fire('Error', 'Something went wrong!', 'error');
                    }
                });
            } else {
                Swal.fire('Cancelled', 'Your data is safe', 'info');
            }
        });
    }
</script>

Quirke.CRM/Views/Master/Suppliers.cshtml
@model SupplierModel

@{
    ViewData["Title"] = "Suppliers";
}

<section class="content pt-3">
    <div class="container-fluid">
        <div class="card card-default color-palette-box">
            <div class="card-header">
                <h1 class="card-title">
                    <b>Supplier List</b>
                </h1>
                <button class="btn btn-primary btn-sm float-right" onclick="funManageSupplier(null)">Add Supplier &nbsp; <i class="fas fa-plus"></i></button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="suppliersTable" class="table table-striped table-bordered" style="width:100%">
                        <thead class="thead-dark">
                            <tr>
                                <th>Sr No.</th>
                                <th>Name</th>
                                <th>Contact Name</th>
                                <th>Contact Email</th>
                                <th>Contact Phone</th>
                                <th>Address</th>
                                <th>Is Active</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="commonModalCenter" tabindex="-1" role="dialog" aria-labelledby="commonModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="divCommonModel"></div>
    </div>
</div>

<!-- Scripts -->
<script src="~/quirke/js/jquery-3.6.0.min.js"></script>

<!-- Add jQuery UI JS -->

<script src="~/quirke/js/jquery-ui.min.js"></script>
<script src="~/quirke/js/bootstrap.bundle.min.js"></script>

<script type="text/javascript">
    var myModal = new bootstrap.Modal(document.getElementById('commonModalCenter'));
    var dtTable;

    $(document).ready(function () {
        funGridSupplier();
        $(window).resize(() => {
            setTimeout(function () {
                $($.fn.dataTable.tables(true)).DataTable().columns.adjust();
            }, 200);
        });
    });

    function funGridSupplier() {
        if (dtTable) {
            dtTable.destroy();
        }
        dtTable = $('#suppliersTable').DataTable({
            "processing": true,
            "serverSide": false,
            "ajax": {
                "url": "@Url.Action("GetSuppliersData", "Master")",
                "type": "GET",
                "datatype": "json"
            },
            "columns": [
                {
                    "data": null,
                    "className": "text-center",
                    "render": function (data, type, full, meta) {
                        return meta.row + 1;
                    }
                },
                { "data": "Name" },
                { "data": "ContactName" },
                { "data": "ContactEmail" },
                { "data": "ContactPhone" },
                { "data": "Address" },
                {
                    "data": "IsActive",
                    "className": "text-center",
                    "render": function (data) {
                        return data ? '<span class="badge badge-success">Active</span>' : '<span class="badge badge-danger">Inactive</span>';
                    }
                },
                {
                    "render": function (data, type, full, meta) {
                        return '<button class="btn btn-secondary btn-sm mr-2" onclick="funManageSupplier(' + full.Id + ')" >Edit  &nbsp; <i class="fas fa-pen"></i></button>' +
                            '<button class="btn btn-danger btn-sm" onclick="funDeleteSupplier(' + full.Id + ')" >Delete  &nbsp; <i class="fas fa-trash"></i></button>';
                    }
                }
            ],
            fixedHeader: true,
            responsive: true,
            scrollCollapse: true,
            scrollY: '50vh',
            scrollX: true,
            deferRender: true,
            scroller: true,
            autoWidth: true,
            layout: {
                topStart: {
                    buttons: [
                        {
                            extend: 'excel',
                            className: 'btn btn-outline-dark btn-sm',
                            exportOptions: {
                                columns: ':not(:last-child)' // Exclude the last column (actions) from the export
                            }
                        },
                        {
                            extend: 'pdf',
                            className: 'btn btn-outline-dark btn-sm',
                            exportOptions: {
                                columns: ':not(:last-child)' // Exclude the last column (actions) from the export
                            }
                        }
                    ]
                },
                bottom: ['paging'],
                bottomStart: null,
                bottomEnd: null,
            }
        });
    }

    function funManageSupplier(_id) {
        $.ajax({
            url: '@Url.Action("ManageSupplier", "Master")',
            type: 'GET',
            dataType: 'html',
            data: {
                id: _id,
            },
            success: function (data) {
                $("#divCommonModel").html('');
                $("#divCommonModel").html(data);
                myModal.show();
            },
            error: function (error) {
                console.error("Error:", error);
            }
        });
    }

    function funDeleteSupplier(_id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "Do you really want to delete this record? This action cannot be undone.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '@Url.Action("DeleteSupplier", "Master")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        id: _id,
                    },
                    success: function (response) {
                        if (response.result) {
                            funGridSupplier();
                            Swal.fire({
                                title: 'Success!',
                                text: response.msg,
                                icon: 'success',
                                confirmButtonText: 'OK'
                            });
                        }
                    },
                    error: function (error) {
                        Swal.fire('Error', 'Something went wrong!', 'error');
                    }
                });
            } else {
                Swal.fire('Cancelled', 'Your data is safe', 'info');
            }
        });
       
    }

    function funCloseModal() {
        funGridSupplier();
        myModal.hide();
    };
</script>

Quirke.CRM/Views/Master/_ManageMasterPartial.cshtml
@model MasterModel

<form asp-action="ManageMaster" method="post" id="frmMaster">
    <div class="modal-body">
        <div class="card-body">
            <input type="hidden" class="form-control" asp-for="MasterTypeId">
            <input type="hidden" class="form-control" asp-for="Id">

            <div class="form-group">
                <label>Name</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer  text-center">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close &nbsp;<i class="fas fa-times"></i></button>
        <button type="submit" class="btn btn-success">Save &nbsp;<i class="fas fa-save"></i></button>
    </div>
</form>


<script src="~/quirke/js/jquery.validate.min.js"></script>
<script src="~/quirke/js/additional-methods.min.js"></script>
<script src="~/quirke/js/jquery.validate.unobtrusive.min.js"></script>

Quirke.CRM/Views/Master/_ManageSuppliersPartial.cshtml
@model SupplierModel

@{
    var title = Model.Id == 0 ? "Create Supplier" : "Edit Supplier";
}
<div class="modal-header">
    <h5 class="modal-title" id="commonModalCenterTitle">@title</h5>
    <button type="button" class="close" aria-label="Close" onclick="funCloseModal();">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<form id="supplierForm" asp-action="ManageSupplier" method="post">
    <div class="modal-body">
        <div class="card-body">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPhone" class="control-label"></label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label mr-5"></label>
                <input asp-for="IsActive" type="checkbox" />
            </div>
        </div>
    </div>
    <div class="modal-footer  text-center">
        <button type="button" class="btn btn-danger" onclick="funCloseModal()">Close &nbsp;<i class="fas fa-times"></i></button>
        <button type="submit" class="btn btn-success">Save &nbsp;<i class="fas fa-save"></i></button>
    </div>

</form>


<script src="~/quirke/js/jquery.validate.min.js"></script>
<script src="~/quirke/js/additional-methods.min.js"></script>
<script src="~/quirke/js/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {

        $('#supplierForm').submit(function (e) {
            e.preventDefault();

            var form = $(this);
            var formData = new FormData(this);

            $.ajax({
                url: form.attr('action'),
                type: form.attr('method'),
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    debugger
                    if (response == null) {
                        return false;
                    }

                    if (response.result) {
                        Swal.fire({
                            title: 'Success!',
                            text: response.msg,
                            icon: 'success',
                            confirmButtonText: 'OK'
                        })
                            .then((result) => {
                                // if (result.isConfirmed) {
                                //     funCloseModal();
                                // }
                            });
                        funCloseModal();
                    } else if (!response.result) {
                        Swal.fire({
                            title: 'Error!',
                            text: response.msg,
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    }
                },
                error: function (xhr, status, error) {
                    console.error("Submission failed: ", error);
                    Swal.fire({
                        title: 'Submission Failed!',
                        text: "There was an issue submitting your request. Please try again.",
                        icon: 'error',
                        confirmButtonText: 'OK'
                    });
                }
            });
        });

    });
</script>

Quirke.CRM/Views/Master/_ViewSuppliersPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}